### FAZER O LOGIN (AGORA VAI FUNCIONAR!)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "admin@empresa.com",
    "senha": "senha_forte_123"
}

### ==============================================
###     CRIAR UM NOVO UTILIZADOR (EX: MECÂNICO)
### ==============================================

# Esta requisição SÓ FUNCIONA se o token for de um ADMIN.
# Certifique-se de que já fez o login como admin para que a variável {{authToken}} tenha um valor.

POST http://localhost:8080/api/funcionarios
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbXByZXNhLmNvbSIsImlhdCI6MTc1MDg2MjEzOCwiZXhwIjoxNzUwODk4MTM4fQ.sG5LIJmn3C9Lp7Ro2n0eJPRS99tY0Plwy45flnMS2Gk


{
    "nome": "Carlos Mecanico",
    "email": "carlos.mecanico@empresa.com",
    "senha": "123",
    "telefone": "912345678",
    "tipoFuncionario": "MECANICO"
}